# Generated by Django 3.2.2 on 2024-10-01 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectofinalpp', '0009_auto_20241001_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
