# Generated by Django 3.2.2 on 2024-10-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0010_empleado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodprov',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='prodprov',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='prodprov',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodprov',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='idCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='idVentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectofinalpp.venta'),
        ),
    ]
