# Generated by Django 3.2.2 on 2024-10-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinalpp', '0011_auto_20241001_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Telefono',
            field=models.CharField(max_length=15),
        ),
    ]
